name: Send Notification
description: Send a notification payload to a designated URL when both the URL and API key are provided.
author: Tien Mai (matidev@outlook.com)

inputs:
  notifyUrl:
    description: "Notify Endpoint URL"
    required: false
  notifyKey:
    description: "Notify API Key"
    required: false
  targetBranch:
    description: 'Target Branch'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Send Notification"
      shell: bash
      env:
        NOTIFY_URL: ${{ inputs.notifyUrl }}
        NOTIFY_KEY: ${{ inputs.notifyKey }}
        TARGET_BRANCH: ${{ inputs.targetBranch }}
      run: |
        if [[ -z "$NOTIFY_URL" || -z "$NOTIFY_KEY" ]]; then
          exit 0
        fi

        if ! [[ "$NOTIFY_URL" =~ ^https?:// ]]; then
          echo "Error: notifyUrl must be a valid HTTP/HTTPS URL."
          exit 1
        fi

        TARGET_BRANCH="${TARGET_BRANCH:-${{ github.ref_name }}}"

        curl -X POST \
             -H "Content-Type: application/json" \
             -H "X-Notify-Key: $NOTIFY_KEY" \
             -d "{
                  \"actor\": \"${{ github.actor }}\",
                  \"event_name\": \"${{ github.event_name }}\",
                  \"job\": \"${{ github.job }}\",
                  \"ref_name\": \"$TARGET_BRANCH\",
                  \"ref_type\": \"${{ github.ref_type }}\",
                  \"repository\": \"${{ github.repository }}\",
                  \"run_number\": \"${{ github.run_number }}\",
                  \"triggering_actor\": \"${{ github.triggering_actor }}\",
                  \"workflow\": \"${{ github.workflow }}\"
                 }" \
             "$NOTIFY_URL" || true
